NWPS-124 - Newsletter
Health-Education-England/hee-cms-platform pull request #196
Opened 2022-03-15 10:06 UTC by Raq-HEE

Hi @sankar-shunmuga / @adaMiclos - this is for the backend piece only. The JS validation is being PR'd seperately.

2022-03-20 13:43 UTC, sankar-shunmuga requested changes
Hi @Raq-HEE , As discussed, please create valuelists per channel

2022-03-20 13:43 UTC, sankar-shunmuga commented on site/components/src/main/resources/META-INF/hst-assembly/overrides/valueListManager.xml
> +        <entry key="newsletterRegions" value="/content/documents/administration/valuelists/newsletterregions"/>
As discussed, please create newsletterRegions valuelists per channel

2022-03-20 13:43 UTC, sankar-shunmuga commented on site/components/src/main/resources/META-INF/hst-assembly/overrides/valueListManager.xml
> +        <entry key="newsletterOrganisations" value="/content/documents/administration/valuelists/newsletterorganisations"/>
As discussed, please create newsletterOrganisations valuelists per channel

2022-03-20 13:43 UTC, sankar-shunmuga commented on site/components/src/main/resources/META-INF/hst-assembly/overrides/valueListManager.xml
> +        <entry key="newsletterProfessions" value="/content/documents/administration/valuelists/newsletterprofessions"/>
As discussed, please create newsletterProfessions valuelists per channel

2022-03-20 13:43 UTC, sankar-shunmuga commented on repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/newsletterorganisations.yaml
> +/content/documents/administration/valuelists/newsletterorganisations:
As discussed, please create valuelists per channel

2022-03-20 13:43 UTC, sankar-shunmuga commented on repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/newsletterprofessions.yaml
> +/content/documents/administration/valuelists/newsletterprofessions:
As discussed, please create valuelists per channel

2022-03-20 13:43 UTC, sankar-shunmuga commented on repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/newsletterregions.yaml
> +/content/documents/administration/valuelists/newsletterregions:
As discussed, please create valuelists per channel

2022-03-21 10:43 UTC, Raq-HEE commented
Thatnks for the review San, discussed with team and wer're going for global valuelists for now.

2022-03-21 10:44 UTC, merged