Bug fix/gibug fix/nwps 1613 fe be publication landing page display amendments
Health-Education-England/hee-cms-platform pull request #513
Opened 2023-08-21 09:46 UTC by FranciscoRuizHEE

2023-08-22 14:50 UTC, smanivasag approved these changes

2023-08-22 14:53 UTC, smanivasag requested changes
@FranciscoRuizHEE - Thanks for the PR.

Not sure why the commit history of the PR contains many commits:

![Screenshot 2023-08-22 at 20 22 25](https://github.com/Health-Education-England/hee-cms-platform/assets/35143542/44711322-2314-4b0f-a529-24c7d27ac191)

Could you create a new PR containing only the necessary commit if possible ? thank you!

2023-08-22 15:27 UTC, FranciscoRuizHEE commented
@smanivasag The first commit is the original change, but there was a double space in other part of the test, so it went back to me from Geraldine, I updated from the master to make sure it works with the last changes and that is why there is the "Merge 'master' branch".  I tried to eliminate the commits, but since it is the changes from Master, they still appeared. You can see in file changes that the one change and it has no conflicts in any other part.

2023-08-23 03:58 UTC, smanivasag commented
> @smanivasag The first commit is the original change, but there was a double space in other part of the test, so it went back to me from Geraldine, I updated from the master to make sure it works with the last changes and avoid conflicts and that is why there is the "Merge 'master' branch". I tried to eliminate the commits, but since it is the changes come from Master, they still appeared. You can see in file changes that the one change and it has no conflicts in any other part.

@FranciscoRuizHEE - Thanks for the details. Usually, when we merge `maser` and resolve conflicts, it would appear as one merge commit. Though the `Files changed` tab shows the correct file change, I am still a little nervous about the commit history and so, for the safer side, created a new PR #521 by cherry-picking only the necessary commit 1b81d65c2f8833e230e197d146687e257860f588. Could you review ?

Closing this PR as this has been superseded by #521, thanks

2023-08-23 03:58 UTC, closed without merging